import React from 'react'
import styles from '../styles/Header.module.scss'
import Navbar from './navbar'
import Banner from './banner'
import Head from 'next/head'

const Header = ({ title, bottom }) => {
	return (
		<div className={styles.header}>
			<Head>
				<title>PCariMovie</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={styles.container}>
				<Navbar />
				<Banner title={title} bottom={bottom} />
			</div>
		</div>
	)
}

export default Header
